export const SPAM_MESSAGES = [
  'This is spam message',
  'More spam',
  'SPAM!!!',
  'I am spam bot',
  'Continue spamming',
  'Another spam message',
  'Do not ignore this spam',
  'Spam coming through',
  'Warning: more spam',
  'Just spamming around',
  'Spam detected',
  'Spamming in progress',
  'You are receiving spam',
  'System generated spam',
  'Automated spam message',
  'This is definitely spam',
  'Incoming spam alert',
  'Random spam text',
  'Spamming since 2025',
  'Unlimited spam mode activated',
];
